<a href="https://colab.research.google.com/github/sofiaholway99/AIvsReal-images/blob/main/TensorFlow_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [2]:
x= tf.ones (shape=(2,1))
print (x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [3]:
y=tf.zeros (shape=(1,2))
print(y)

tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)


In [4]:
z=tf.random.normal (shape=(3,1), mean=0, stddev=1.)
print(z)

tf.Tensor(
[[-0.01730062]
 [ 0.7748694 ]
 [ 2.7124777 ]], shape=(3, 1), dtype=float32)


In [11]:
v = tf.Variable(initial_value=tf.random.normal (shape=(3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-2.4145112 ],
       [ 0.50513506],
       [-0.03603207]], dtype=float32)>


In [13]:
v.assign(tf.ones((3, 1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [14]:
v[0, 0].assign(3.)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

In [15]:
v.assign_add(tf.ones((3, 1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>

In [16]:
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape () as tape:
  result = tf.square(input_var)

gradient = tape.gradient(result, input_var)

#Using GradientTape with constant tensor imputs

In [3]:
input_const= tf.constant(3.)
with tf.GradientTape () as tape:
  tape.watch(input_const)
  result = tf.square(input_const)

gradient = tape.gradient(result, input_const)
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


You squared 3 to get 9.

Then you asked: “If I nudge 3 slightly up or down, how fast does 9 change?”

Answer: 6 (because near 3, squaring changes pretty quickly).

-------
result = tf.square(input_const)
Computes:

result = 3² = 9

So inside the tape, it recorded the operation “square”.

gradient = tape.gradient(result, input_const)
Now you ask the tape:

“What’s the derivative of result with respect to input_const?”

Since result = x², the derivative is:

(x²)' = 2x

At x = 3, that’s: 2 * 3 = 6

✅ So gradient will be 6.0

## Difference between a tf.constant and a tf.Variable is:

tf.constant = a fixed number/tensor (TensorFlow treats it like “this won’t change”)

tf.Variable = a changeable number/tensor (made to be updated during training)

#Example: what is the acceleration?
Mesure the position of falling apple along a vertical axis over time.



In [4]:
time = tf.Variable(0.)
with tf.GradientTape () as outer_tape:   # will compute "derivative of the derivative" (9.8t)' = 9.8
  with tf.GradientTape () as inner_tape: # will compute first derivative (4.9t^2)'=4.9*2*t
    position = 4.9 * time**2
  speed = inner_tape.gradient(position, time)
acceleration = outer_tape.gradient(speed, time)

print(speed)
print(acceleration)
print(time)
print(position)

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(9.8, shape=(), dtype=float32)
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>
tf.Tensor(0.0, shape=(), dtype=float32)
